In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('ventas_videojuegos.csv')

In [7]:
df.head()

,nombre,plataforma,genero,anio,editora,ventas_na,ventas_eu,ventas_jp,ventas_otros,ventas_global
0,The Elder Scrolls V: Skyrim,X360,Rol,2011.0,Bethesda,7.12,6.35,6.99,2.26,22.72
1,Assassin's Creed Odyssey,PS4,Accion,2018.0,Ubisoft,3.85,2.99,0.64,0.55,8.03
2,Fall Guys,PS4,Plataformas,2020.0,Devolver Digital,0.40,0.26,0.15,0.08,0.89
3,Tekken 7,PS4,Lucha,2017.0,Bandai Namco,1.09,0.90,1.10,0.33,3.42
4,It Takes Two,PS4,Aventura,2021.0,Electronic Arts,1.11,0.84,0.30,0.20,2.45

In [8]:
df.tail()

,nombre,plataforma,genero,anio,editora,ventas_na,ventas_eu,ventas_jp,ventas_otros,ventas_global
199,Elden Ring,PS5,Rol,2022.0,Bandai Namco,2.25,1.82,2.81,0.61,7.49
200,Gran Turismo Sport,PS4,Carreras,2017.0,NaN,0.33,0.32,0.06,0.05,0.76
201,The Last of Us,PS3,Aventura,2013.0,Sony,3.09,2.00,0.87,0.41,6.37
202,Assassin's Creed II,X360,Accion,2009.0,Ubisoft,3.92,2.72,1.24,0.70,8.58
203,Call of Duty: Modern Warfare 2,X360,Disparos,2009.0,Activision,5.15,3.59,0.41,1.00,10.15

In [9]:
df.shape

(204, 10)