In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('titanic.csv')

In [3]:
df.head()

   sobrevivio  clase  genero  edad  hermanos_conyuges  padres_hijos
0           0      3  hombre    22                  1             0
1           1      1   mujer    38                  1             0
2           1      3   mujer    26                  0             0
3           1      1   mujer    35                  1             0
4           0      3  hombre    35                  0             0

In [4]:
df.shape

(714, 6)

In [5]:
df.tail()

     sobrevivio  clase  genero  edad  hermanos_conyuges  padres_hijos
709           0      3   mujer    39                  0             5
710           0      2  hombre    27                  0             0
711           1      1   mujer    19                  0             0
712           1      1  hombre    26                  0             0
713           0      3  hombre    32                  0             0